kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-filestore-csi-resizer-binding
subjects:
  - kind: ServiceAccount
    name: gcp-filestore-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: gcp-filestore-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
